import turtle

screen = turtle.Screen()
screen.screensize(500, 500)
screen.bgcolor('deepskyblue2')

t=turtle.Turtle()
t.speed(0)\

#spring
t.penup()
t.goto(0,150)
t.pendown()
t.write('Spring', font=('Arial', 50, "bold"), align="center")
t.penup()
t.goto(0, -10)

#grass
t.penup()
t.goto(-5000,-100)
t.pendown()
t.fillcolor('forestgreen')
t.pencolor("forestgreen")
t.begin_fill()
t.goto(5000,-100)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-100)
t.end_fill()

#sun
t.penup()
t.goto(-225,225)
t.pendown()
t.fillcolor("gold1")
t.pencolor("gold1")
t.begin_fill()
t.circle(60)
t.end_fill()

#cloud
t.penup()
t.goto(50,230)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(100,230)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(75,260)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

#tree stump
t.penup()
t.goto(-210,-100)
t.pendown()
t.pencolor('brown')
t.fillcolor('brown')
t.begin_fill()
t.forward(25)
t.left(90)
t.forward(100)
t.left(90)
t.forward(25)
t.left(90)
t.forward(100)
t.end_fill()

#treeleaves
t.pencolor('green4')
t.penup()
t.goto(-250,0)
t.pendown()
t.fillcolor('green4')
t.begin_fill()
t.circle(30)
t.end_fill()
t.pencolor('green4')
t.penup()
t.goto(-200, 0)
t.begin_fill()
t. fillcolor('green4')
t. begin_fill()
t.circle (30)
t.end_fill()
t.pencolor('green4')
t. penup()
t.goto(-225,35)
t.pendown()
t.fillcolor('green4')
t.begin_fill()
t.circle(30)
t.end_fill()

#pond
t.penup()
t.goto(-245,-225)
t.pendown()
t.fillcolor("blue")
t.pencolor("blue")
t.begin_fill()
t.circle(80)
t.end_fill()

#flower
t.penup()
t.goto(50,-250)
t.pendown()
t.fillcolor("darkorchid1")
t.pencolor("darkorchid1")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(40,-260)
t.pendown()
t.pencolor("darkorchid1")
t.fillcolor("darkorchid1")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.penup()
t.goto(30,-250)
t.pendown()
t.fillcolor("darkorchid1")
t.pencolor("darkorchid1")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(40,-240)
t.pendown()
t.fillcolor("darkorchid1")
t.pencolor("darkorchid1")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(40,-250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(10)
t.end_fill()

#2ndflower
t.penup()
t.goto(150,-150)
t.pendown()
t.fillcolor("cornflowerblue")
t.pencolor("cornflowerblue")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(140,-160)
t.pendown()
t.pencolor("cornflowerblue")
t.fillcolor("cornflowerblue")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.penup()
t.goto(130,-150)
t.pendown()
t.fillcolor("cornflowerblue")
t.pencolor("cornflowerblue")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(140,-140)
t.pendown()
t.fillcolor("cornflowerblue")
t.pencolor("cornflowerblue")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(140,-150)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(10)
t.end_fill()

#bush
t.pencolor('darkgreen')
t.penup()
t.goto(259,-90)
t.pendown()
t.fillcolor('darkgreen')
t.begin_fill()
t.circle(50)
t.end_fill()
t.pencolor('darkgreen')
t.penup()
t.goto(200, -90)
t.begin_fill()
t.fillcolor('darkgreen')
t.begin_fill()
t.circle (50)
t.end_fill()

#well
t.fillcolor("sienna4")
t.pencolor('sienna4')
t.begin_fill()
t.penup()
t.goto(5,-10)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.end_fill()
t.penup()


turtle.done()